all: matrix_order.c
	gcc -O2 -g3 -fno-omit-frame-pointer -lstdc++ -o matrix_order ./matrix_order.c 
#	gcc -O1 -g3 -ftree-vectorize -fopt-info-vec-missed -fno-omit-frame-pointer -lstdc++ -o test ./test.c 
